llm_config = {
    "small_model": "gpt-4o-mini",
    "large_model": "gpt-4o-mini",
    "system_prompt": """You are a social media content strategist. Your task is to create a ready-to-use social media post aimed at healthcare professionals. The post should summarize the key takeaways from a webpage scraping in a concise, bullet-point format, emphasizing actionable insights and recent updates relevant to clinical practice.

The tone should be professional yet conversational, making the content easy to digest and engaging. Avoid directly addressing the audience as healthcare professionals, but subtly encourage discussion. Include a link to the source and relevant hashtags to boost visibility. Output the post as plain text, not Markdown.

Here is an example:
🔍 Recent findings highlight a critical link between acute kidney injury (AKI) and dementia risk:

- AKI history doubles the risk of developing dementia, drawing attention to the need for early monitoring.
- This study followed over 305,000 individuals aged 65+ in Stockholm, uncovering 47,938 cases of dementia over 12 years.
- Notably, AKI increased the occurrence of Lewy body dementia (DLB) by 88%, vascular dementia by 47%, and Alzheimer’s disease (AD) by 31%.
- Severe AKI linked to hospitalization poses a 61% higher risk than less severe cases.
- A dose-response relationship exists between the severity of AKI and dementia risk, reinforcing the need for comprehensive prevention strategies.
- Age stratification revealed a staggering FOUR-FOLD INCREASE IN DLB AND PDD RISK for those over 85 years.
These insights emphasize the importance of monitoring kidney function as part of dementia prevention strategies. Let's discuss how this can be integrated into clinical practice!

For more details, check out the full study here: https://www.neurology.org/doi/10.1212/WNL.0000000000209751

#AcuteKidneyInjury #DementiaRisk #Neuroscience #AgingPopulation #HealthcareResearch #PublicHealth #ClinicalPractice""",
     "hashtags": [
    "GeneralResearch",
    "ClinicalTrials",
    "MedicalDevices",
    "DigitalHealth",
    "Telemedicine",
    "HealthTech",
    "AIInHealthcare",
    "Cardiology",
    "Oncology",
    "Neurology",
    "Endocrinology",
    "InfectiousDiseases",
    "Pulmonology",
    "Rheumatology",
    "Gastroenterology",
    "Dermatology",
    "Hematology",
    "Nephrology",
    "Ophthalmology",
    "ENT",
    "Pediatrics",
    "Geriatrics",
    "Psychiatry",
    "Surgery",
    "Orthopedics",
    "Radiology",
    "Pathology",
    "Anesthesiology",
    "CriticalCare",
    "EmergencyMedicine",
    "PrimaryCare",
    "FamilyMedicine",
    "MedicalEthics",
    "HealthPolicy",
    "HealthcareRegulation",
    "Reimbursement",
    "CME",
    "MedicalEducation",
    "MedicalConferences",
    "MergersAcquisitions",
    "DrugDevelopment",
    "MarketTrends",
    "PatientSupport",
    "HealthEquity",
    "HealthAccess",
    "PublicHealth",
    "Genomics",
    "PersonalizedMedicine",
    "Biotechnology",
    "WearableTech",
    "mHealth",
    "RemoteMonitoring",
    "Telehealth",
    "HealthcareInnovation",
    "EHR",
    "PatientEngagement",
    "BigDataInHealth",
    "VRInHealthcare",
    "ARInHealthcare",
    "BlockchainInHealth",
    "CybersecurityInHealth",
    "HealthcareRobotics",
    "3DPrintingMedicine",
    "RegenerativeMedicine",
    "PrecisionMedicine",
    "MentalHealth",
    "SleepMedicine",
    "PalliativeCare",
    "PainManagement",
    "Nutrition",
    "LifestyleMedicine",
    "HealthEconomics",
    "PopulationHealth",
    "SocialDeterminantsOfHealth",
    "MedicalImaging",
    "VirtualCare",
    "HealthDataPrivacy",
    "HealthStartups",
    "HealthEntrepreneurship",
    "GlobalHealth",
    "DisasterMedicine",
    "TravelMedicine",
    "OccupationalHealth",
    "SportsMedicine",
    "IntegrativeMedicine",
    "AlternativeMedicine",
    "MedicalHistory",
    "HealthcareDesign",
    "HealthMarketing",
    "Pharmacovigilance",
    "HealthOutcomes",
    "MedicalStatistics",
    "PatientSafety",
    "SustainableHealth",
    "EnvironmentalHealth",
    "HealthSupplyChain",
    "HealthLiteracy",
    "PatientEducation"
]
 }
