name: Update every 4 hours

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grants the necessary permissions to push changes

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run the Sifted script
#        run: |
#          python scripts/update_sifted.py
#
#      - name: Run the Meds script
#        run: |
#          python scripts/update_meds.py
#          
      - name: Printenv
        run: |
          printenv
        env:
          OPENAI_API_KEY: ${{ secrets.MY_OPENAI_API_KEY }}

      - name: Test OpenAI API Key
        run: |
          python -c "import os; print('OpenAI API Key:', os.getenv('OPENAI_API_KEY'))"
        env:
          OPENAI_API_KEY: ${{ secrets.MY_OPENAI_API_KEY }}
      
      # - name: Run the LLM processing script
      #   run: |
      #     python scripts/llm.py
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated databases and log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
