name: Scrape and Update Firestore

on:
  schedule:
    # Weekdays (Monday to Friday) during working hours (every 15 minutes)
    - cron: '*/15 9-17 * * 1-5'  # Scrape every 15 minutes from 09:00 to 17:59, Monday to Friday

    # Weekdays (Monday to Friday) during non-working hours (every 1 hour)
    - cron: '0 18-23 * * 1-5'  # Scrape every hour from 18:00 to 23:59, Monday to Friday

    # Weekdays (Monday to Friday) during late night/early morning (every 2 hours)
    - cron: '0 0,2,4,6,8 * * 1-5'  # Scrape every 2 hours from midnight to 08:59, Monday to Friday

    # Weekends (Saturday and Sunday) during the day (every 2 hours)
    - cron: '0 9,11,13,15,17,19,21,23 * * 6,0'  # Scrape every 2 hours from 09:00 to 23:59, Saturday and Sunday

    # Weekends (Saturday and Sunday) during the night (every 4 hours)
    - cron: '0 0,4,8 * * 6,0'  # Scrape every 4 hours from midnight to 08:59, Saturday and Sunday

  workflow_dispatch:  # Allows manual triggering of the workflow
  
permissions:
  contents: write  # Grants the necessary permissions to push changes

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run the Sifted script
        run: |
          python scripts/update_sifted.py
          
      - name: Run the Meds script
        run: |
          python scripts/update_meds.py

      - name: Run the Scape script
        run: |
          python scripts/update_scape.py
        env:
          OPENAI_API_KEY: ${{ secrets.MY_OPENAI_API_KEY }}

      - name: Run the NICE script
        run: |
          python scripts/update_nice.py

      - name: Run the NIH script
        run: |
          python scripts/update_nih_cr.py
          
      - name: Run the Digital Health Script
        run: |
          python scripts/update_digital_health.py
      
      - name: Run the UK Tech script
        run: |
          python scripts/update_uktech.py

      - name: Run the LLM processing script
        run: |
          python scripts/llm.py
        env:
          OPENAI_API_KEY: ${{ secrets.MY_OPENAI_API_KEY }}
      # - name: Upload to Firebase
      #   env:
      #     FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #   run: |
      #     echo $FIREBASE_SERVICE_ACCOUNT > firebase_creds.json
      #     python3 scripts/upload_to_firebase.py databases/llm.csv

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . -- ':!firebase_creds.json'  # Exclude firebase_creds.json
          git commit -m "Updated databases and log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
